# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('starttime', models.DateTimeField(blank=True, db_column='startTime', null=True)),
                ('endtime', models.DateTimeField(blank=True, db_column='endTime', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('salestarttime', models.DateTimeField(blank=True, db_column='saleStartTime', null=True)),
                ('saleendtime', models.DateTimeField(blank=True, db_column='saleEndTime', null=True)),
                ('eventname', models.CharField(blank=True, db_column='eventName', max_length=255, null=True)),
                ('eventid', models.CharField(db_column='eventID', max_length=255, primary_key=True, serialize=False)),
                ('subgenre', models.CharField(blank=True, max_length=255, null=True)),
                ('genre', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('urlimg', models.CharField(blank=True, db_column='urlImg', max_length=255, null=True)),
                ('urlevent', models.CharField(blank=True, db_column='urlEvent', max_length=255, null=True)),
                ('urlbooking', models.CharField(blank=True, db_column='urlBooking', max_length=255, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'events',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('historyid', models.CharField(db_column='historyid', max_length=255, primary_key=True, serialize=False)),
                ('invited', models.TextField(blank=True, null=True)),
                ('acceptedinvites', models.TextField(blank=True, db_column='acceptedInvites', null=True)),
                ('declinedinvite', models.TextField(blank=True, db_column='declinedInvite', null=True)),
                ('startlocations', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('fbname', models.CharField(blank=True, max_length=255, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('interests', models.TextField(blank=True, null=True)),
                ('transportationpref', models.CharField(blank=True, db_column='transportationPref', max_length=255, null=True)),
                ('homelat', models.FloatField(blank=True, null=True)),
                ('homelong', models.FloatField(blank=True, null=True)),
                ('officelat', models.FloatField(blank=True, null=True)),
                ('officelong', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
